### PR TITLE
Fixed bugs with saving Chapter Ratings and List Due tasks prompt

### LINKED ISSUE #67: Chapter Deadlines are not updated into local data files, and cannot be retrieved when Chapters are loaded.

### PR DESCRIPTION
**Pull request by Darticune**
Fixes #67

### CODE REVIEW

File: src/main/java/commands/ListDueCommand.java [hunk 1]
```diff
@@ -34,14 +31,28 @@ private void loadAllChapters(Storage storage, Ui ui) {
...
+            if (Scheduler.isDeadlineDue(deadline)) {
                 dueChapters.add(chapter);
             }
         }
-        ui.showToUser("The chapters you have due by today are:");
-        for (Chapter dueChapter : dueChapters) {
-            ui.showToUser(dueChapter.toString());
+        if (dueChapters.size() == 0) {
+            ui.showToUser("You have no tasks due today! Please check back again tomorrow!");
+        } else {
```
Comment (Jane-Ng) [inline src/main/java/commands/ListDueCommand.java]: I think for this, you can have a return after line 41 so that you would not need the else part. Then the rest of the code will follow. Something like this:
if (dueChapters.size() == 0) {
    ui.showToUser("You have no tasks due today! Please check back again tomorrow!");
    return;
}
// rest of the code

File: src/main/java/commands/ListDueCommand.java [hunk 2]
```diff
@@ -34,14 +31,28 @@ private void loadAllChapters(Storage storage, Ui ui) {
...
+            System.out.print("The chapter");
```
Comment (Jane-Ng) [inline src/main/java/commands/ListDueCommand.java]: you can use ui.showToUser

File: src/main/java/commands/ListDueCommand.java [hunk 3]
```diff
@@ -34,14 +31,28 @@ private void loadAllChapters(Storage storage, Ui ui) {
...
+            if (dueChapters.size() > 1) {
+                System.out.print("s");
+            }
+            System.out.print(" you have due by today ");
```
Comment (Jane-Ng) [inline src/main/java/commands/ListDueCommand.java]: you can use ui.showToUser

File: src/main/java/commands/ListDueCommand.java [hunk 4]
```diff
@@ -34,14 +31,28 @@ private void loadAllChapters(Storage storage, Ui ui) {
...
         }
-        ui.showToUser("The chapters you have due by today are:");
-        for (Chapter dueChapter : dueChapters) {
-            ui.showToUser(dueChapter.toString());
+        if (dueChapters.size() == 0) {
+            ui.showToUser("You have no tasks due today! Please check back again tomorrow!");
+        } else {
+            System.out.print("The chapter");
+            if (dueChapters.size() > 1) {
+                System.out.print("s");
```
Comment (Jane-Ng) [inline src/main/java/commands/ListDueCommand.java]: you can use ui.showToUser

File: src/main/java/commands/ReviseCommand.java [hunk 5]
```diff
@@ -121,19 +126,14 @@ public void execute(Ui ui, Access access, Storage storage)
         return repeatCards;
     }
 
-    private int repeatRevision(Ui ui, ArrayList<Card> cards, int count) {
+    private void repeatRevision(Ui ui, ArrayList<Card> cards, int count) {
```
Comment (woozije) [inline src/main/java/commands/ReviseCommand.java]: Need this to be int for assertion

File: src/main/java/commands/ReviseCommand.java [hunk 6]
```diff
@@ -79,17 +88,13 @@ public void execute(Ui ui, Access access, Storage storage)
...
         for (Card c : allCards) {
-            ui.showToUser("\nQuestion " + count + ":");
-            ui.showCardRevision(c);
-            String input = ui.getRating();
-            repeatCards = rateCard(ui, repeatCards, c, input);
-            count++;
+            count = reviseCard(count, c, ui, repeatCards);
         }
-        int remainingCards = repeatRevision(ui, repeatCards, count);
-        assert remainingCards == 0 : "Cards were left in repeat revision";
```
Comment (woozije) [inline src/main/java/commands/ReviseCommand.java:90]: Need this for assertion

File: src/main/java/commands/ListDueCommand.java [hunk 7]
```diff
@@ -1,29 +1,26 @@
...
+import java.time.LocalDate;
 import java.util.ArrayList;
 
 public class ListDueCommand extends Command {
-    public static final String COMMAND_WORD = "listDue";
-    ArrayList<Chapter> dueChapters = new ArrayList<>();
-
-    public ArrayList<Module> modules;
-    public ArrayList<Chapter> allChapters = new ArrayList<>();
+    public static final String COMMAND_WORD = "due";
```
Comment (woozije) [inline src/main/java/commands/ListDueCommand.java:17]: Perhaps could also add MESSAGE_USAGE like other commands?

File: src/main/java/parser/Parser.java [hunk 8]
```diff
@@ -34,6 +34,8 @@ public static Command parse(String fullCommand, Access access)
         String commandType = commandTypeAndArgs[0].trim().toLowerCase();
         String commandArgs = commandTypeAndArgs[1].trim();
 
+        System.out.println("Command Type: " + commandType);
```
Comment (woozije) [inline src/main/java/parser/Parser.java:37]: Perhaps could use ui.showToUser as well. And could maybe change to "Command entered: " instead? As some commands may be invalid.

File: src/main/java/storage/Storage.java [hunk 9]
```diff
@@ -129,6 +131,73 @@ public void createChapter(String chapterName, String moduleName) {
...
+        try {
+            Scanner s = new Scanner(f);
+            if (s.hasNext()) {
+                return s.nextLine();
+            } else {
+                return "Invalid Date";
+            }
+        } catch (FileNotFoundException e) {
+            return "Does not exist";
+        }
```
Comment (woozije) [inline src/main/java/storage/Storage.java:149]: Perhaps could close scanner here?

File: src/main/java/storage/Storage.java [hunk 10]
```diff
@@ -129,6 +131,73 @@ public void createChapter(String chapterName, String moduleName) {
...
+                    System.out.println("Module: " + module + "; " + "Chapter: " + target);
+                    System.out.println("has a corrupted deadline. Please revise it ASAP! It will be considered due!\n");
+                    dueChapters.add(new DueChapter(module, new Chapter(target, Scheduler.parseDate(deadline))));
+                } else if (deadline.equals("Does not exist")) {
+                    if (missingDueFileCheck(module, target)) {
+                        deadline = "Invalid Date";
+                        System.out.println("\nThe chapter:");
+                        System.out.println("Module: " + module + "; " + "Chapter: " + target);
+                        System.out.print("has a corrupted deadline. Please revise it ASAP!");
+                        System.out.println(" It will be considered due!\n");
```
Comment (woozije) [inline src/main/java/storage/Storage.java:194]: Perhaps could use ui.showToUser or create a method specifically for printing these in Ui?

File: src/main/java/commands/ListDueCommand.java (hunk 3 above)
Comment (Darticune) [reply src/main/java/commands/ListDueCommand.java]: I cannot, because ui.showToUser enforces newline after printing string. I will use format string in the next iteration.

File: src/main/java/commands/ListDueCommand.java (hunk 4 above)
Comment (Darticune) [reply src/main/java/commands/ListDueCommand.java]: I cannot, because ui.showToUser enforces newline after printing string. I will use format string in the next iteration.

File: src/main/java/commands/ListDueCommand.java (hunk 2 above)
Comment (Darticune) [reply src/main/java/commands/ListDueCommand.java]: I cannot, because ui.showToUser enforces newline after printing string. I will use format string in the next iteration.
