### PR TITLE
Fix revise command to get cards based on access

### LINKED ISSUE #57: Modify Revise command to get cards based on Access

### PR DESCRIPTION
**Pull request by woozije**
Fixes #57

### CODE REVIEW

File: src/main/java/parser/Parser.java [hunk 1]
```diff
@@ -212,11 +216,26 @@ private static String parseAnswer(String arg) throws InvalidInputException {
...
+            chapterIndex = Integer.parseInt(commandArgs) - 1;
+            chapter = access.getModule().getChapters().getChapter(chapterIndex);
+        } catch (NumberFormatException e) {
+            throw new IncorrectAccessLevelException("The index for chapter should be an integer.\n"
+                    + ReviseCommand.MESSAGE_USAGE);
+        } catch (IndexOutOfBoundsException e) {
+            throw new IncorrectAccessLevelException("The chapter is not found.\n");
         }
-        return new ReviseCommand(commandArgs);
+        return new ReviseCommand(chapter);
```
Comment (Jane-Ng) [inline src/main/java/parser/Parser.java]: will getting the chapter in ReviseCommand be better? means you pass the chapterIndex in the ReviseCommand()
